package org.bullithulli.rpyparser;

public enum RENPY_SYMBOL_TYPE {
    ROOT_FILE, RENPY_LABEL, RENPY_SPEAKER_TEXT, RENPY_NO_SPEAKER_TEXT, RENPY_GENERIC_NON_BLOCK_SYMBOLS, RENPY_GENERIC_BLOCK_SYMBOLS, RENPY_JUMP, RENPY_RETURN, RENPY_CALL
}
