package org.bullithulli.rpyparser;

public enum RENPY_SYMBOL_TYPE {
    ROOT_FILE, RENPY_LABEL, RENPY_SCREEN, RENPY_SPEAKER_TEXT, RENPY_NO_SPEAKER_TEXT, RENPY_CALL, RENPY_LINE_COMMENT, RENPY_JUMP, RENPY_RETURN
}
